cmd: "sh .scripts/deploy.sh"
name: "Deploy Retail"
args:
   - "{FILE_ACTIVE_PATH}"

errorMatch:
   - <ERROR>(?<message>.+)
warningMatch:
   - <WARNING>(?<message>.+)

targets:
   PTR:
      name: "Deploy PTR"
      cmd: "sh .scripts/deploy.sh"
      args:
         - "-p"
