require "busted.runner"()

insulate("AddonLoader", function()
	it("should not crash", function()
		print(1,lfs.currentdir())
		assert.has_no.errors(function() loadfile(".specs/AddonLoader.lua")().LoadToc("RCLootCouncil.toc") end)
	end)
end)

insulate("AddonLoader", function()
	it("should load RCLootCouncil", function()
		print(2,lfs.currentdir())
		loadfile(".specs/AddonLoader.lua")().LoadToc("RCLootCouncil.toc")
		assert.truthy(_G.RCLootCouncil)
	end)
end)

insulate("AddonLoader", function()
	it("should load files without errors", function()
		local s = spy.on(_G, "_errorhandler")
		loadfile(".specs/AddonLoader.lua")().LoadToc("RCLootCouncil.toc")
		WoWAPI_FireEvent("ADDON_LOADED", "RCLootCouncil")
		assert.spy(s).was_not.called()
	end)

	it("should be enabled without issues", function()
		local s = spy.on(_G, "_errorhandler")
		_G.IsLoggedIn = spy.new(function() return true end)
		WoWAPI_FireEvent("PLAYER_LOGIN", "RCLootCouncil")
		assert.truthy(_G.RCLootCouncil)
		assert.True(_G.RCLootCouncil.TradeUI:IsEnabled())
		assert.spy(s).was_not.called()
	end)
end)
