-- Not really a WoW API, but Enums are gathered here as they're a depency of other APIs
Enum = {
	ItemWeaponSubclass = {
		Axe1H = 0,
		Axe2H = 1,
		Bows = 2,
		Guns = 3,
		Mace1H = 4,
		Mace2H = 5,
		Polearm = 6,
		Sword1H = 7,
		Sword2H = 8,
		Warglaive = 9,
		Staff = 10,
		Bearclaw = 11,
		Catclaw = 12,
		Unarmed = 13,
		Generic = 14,
		Dagger = 15,
		Thrown = 16,
		Obsolete3 = 17,
		Crossbow = 18,
		Wand = 19,
		Fishingpole = 20,
	},
	ItemMiscellaneousSubclass = {
		Junk = 0,
		Reagent = 1,
		CompanionPet = 2,
		Holiday = 3,
		Other = 4,
		Mount = 5,
		MountEquipment = 6,
	},
	ItemClass = {
		Consumable = 0,
		Container = 1,
		Weapon = 2,
		Gem = 3,
		Armor = 4,
		Reagent = 5,
		Projectile = 6,
		Tradegoods = 7,
		ItemEnhancement = 8,
		Recipe = 9,
		CurrencyTokenObsolete = 10,
		Quiver = 11,
		Questitem = 12,
		Key = 13,
		PermanentObsolete = 14,
		Miscellaneous = 15,
		Glyph = 16,
		Battlepet = 17,
		WoWToken = 18,
	},
	ItemArmorSubclass = {
		Generic = 0,
		Cloth = 1,
		Leather = 2,
		Mail = 3,
		Plate = 4,
		Cosmetic = 5,
		Shield = 6,
		Libram = 7,
		Idol = 8,
		Totem = 9,
		Sigil = 10,
		Relic = 11,
	},
	ItemReagentSubclass = {
		Reagent = 0,
		Keystone = 1,
		ContextToken = 2,
	},
	ItemBind = {
		None = 0,
		OnAcquire = 1,
		OnEquip = 2,
		OnUse = 3,
		Quest = 4,
		Unused1 = 5,
		Unused2 = 6,
		ToWoWAccount = 7,
		ToBnetAccount = 8,
		ToBnetAccountUntilEquipped = 9,
	},
	ItemQuality = {
		Poor = 0,
		Common = 1,
		Uncommon = 2,
		Rare = 3,
		Epic = 4,
		Legendary = 5,
		Artifact = 6,
		Heirloom = 7,
		WoWToken = 8,
	},
	ItemQualityMeta = {
		NumValues = 9,
	},

	SeasonID = {
		NoSeason = 0,
		SeasonOfMastery = 1,
		SeasonOfDiscovery = 2,
		Hardcore = 3,
		Fresh = 11,
		FreshHardcore = 12,
	},
	LootMethod = {
		Freeforall = 0,
		Roundrobin = 1,
		Masterlooter = 2,
		Group = 3,
		Needbeforegreed = 4,
		Personal = 5,
	},
}
