--- Constants.lua
local _, addon = ...

addon.BTN_SLOTS = {
	INVTYPE_HEAD 				= "AZERITE",
	INVTYPE_CHEST 				= "AZERITE",
	INVTYPE_ROBE 				= "AZERITE",
	INVTYPE_SHOULDER 			= "AZERITE",
	INVTYPE_2HWEAPON			= "WEAPON",
	INVTYPE_WEAPONMAINHAND	= "WEAPON",
	INVTYPE_WEAPONOFFHAND	= "WEAPON",
	INVTYPE_WEAPON				= "WEAPON",
	INVTYPE_THROWN				= "WEAPON",
	INVTYPE_RANGED				= "WEAPON",
	INVTYPE_RANGEDRIGHT		= "WEAPON",
	INVTYPE_HOLDABLE			= "WEAPON",
}
