--- subTypeLookup.lua  a table that stores subType in all in-game localizations
-- @author Safetee
-- Create Date : 22/10/2017

--[[
Entries:
	"Cloth"
	"Leather"
	"Mail"
	"Plate"
	"Shields"
	"Bows"
	"Crossbows"
	"Daggers"
	"Guns"
	"Fist Weapons"
	"One-Handed Axes"
	"One-Handed Maces"
	"One-Handed Swords"
	"Polearms"
	"Staves"
	"Two-Handed Axes"
	"Two-Handed Maces"
	"Two-Handed Swords"
	"Wands"
	"Warglaives"
	"Artifact Relic"
	"Miscellaneous"
--]]

RCSubTypeLookup = {
	["deDE"] = {
		["Bogen"] = "Bows",
		["Einhandschwerter"] = "One-Handed Swords",
		["Einhandäxte"] = "One-Handed Axes",
		["Artefaktrelikt"] = "Artifact Relic",
		["Einhandstreitkolben"] = "One-Handed Maces",
		["Stangenwaffen"] = "Polearms",
		["Armbrüste"] = "Crossbows",
		["Platte"] = "Plate",
		["Schusswaffen"] = "Guns",
		["Leder"] = "Leather",
		["Verschiedenes"] = "Miscellaneous",
		["Zauberstäbe"] = "Wands",
		["Zweihandäxte"] = "Two-Handed Axes",
		["Dolche"] = "Daggers",
		["Stoff"] = "Cloth",
		["Zweihandstreitkolben"] = "Two-Handed Maces",
		["Kette"] = "Mail",
		["Faustwaffen"] = "Fist Weapons",
		["Kriegsgleven"] = "Warglaives",
		["Schilde"] = "Shields",
		["Zweihandschwerter"] = "Two-Handed Swords",
		["Stäbe"] = "Staves",
	},
	["enUS"] = {
		["One-Handed Axes"] = "One-Handed Axes",
		["Artifact Relic"] = "Artifact Relic",
		["One-Handed Swords"] = "One-Handed Swords",
		["Staves"] = "Staves",
		["Crossbows"] = "Crossbows",
		["Plate"] = "Plate",
		["One-Handed Maces"] = "One-Handed Maces",
		["Warglaives"] = "Warglaives",
		["Shields"] = "Shields",
		["Polearms"] = "Polearms",
		["Daggers"] = "Daggers",
		["Bows"] = "Bows",
		["Two-Handed Swords"] = "Two-Handed Swords",
		["Miscellaneous"] = "Miscellaneous",
		["Leather"] = "Leather",
		["Cloth"] = "Cloth",
		["Guns"] = "Guns",
		["Fist Weapons"] = "Fist Weapons",
		["Mail"] = "Mail",
		["Wands"] = "Wands",
		["Two-Handed Maces"] = "Two-Handed Maces",
		["Two-Handed Axes"] = "Two-Handed Axes",
	},
	["esES"] = {
		["Armas de asta"] = "Polearms",
		["Reliquia de artefacto"] = "Artifact Relic",
		["Espadas de dos manos"] = "Two-Handed Swords",
		["Placas"] = "Plate",
		["Espadas de una mano"] = "One-Handed Swords",
		["Arcos"] = "Bows",
		["Mazas de dos manos"] = "Two-Handed Maces",
		["Cuero"] = "Leather",
		["Armas de fuego"] = "Guns",
		["Ballestas"] = "Crossbows",
		["Hachas de dos manos"] = "Two-Handed Axes",
		["Escudos"] = "Shields",
		["Miscelánea"] = "Miscellaneous",
		["Dagas"] = "Daggers",
		["Varitas"] = "Wands",
		["Tela"] = "Cloth",
		["Malla"] = "Mail",
		["Armas de puño"] = "Fist Weapons",
		["Gujas de guerra"] = "Warglaives",
		["Hachas de una mano"] = "One-Handed Axes",
		["Mazas de una mano"] = "One-Handed Maces",
		["Bastones"] = "Staves",
	},
	["esMX"] = {
		["Armas de asta"] = "Polearms",
		["Reliquia de artefacto"] = "Artifact Relic",
		["Espadas de dos manos"] = "Two-Handed Swords",
		["Placas"] = "Plate",
		["Espadas de una mano"] = "One-Handed Swords",
		["Arcos"] = "Bows",
		["Mazas de dos manos"] = "Two-Handed Maces",
		["Cuero"] = "Leather",
		["Armas de fuego"] = "Guns",
		["Ballestas"] = "Crossbows",
		["Hachas de dos manos"] = "Two-Handed Axes",
		["Escudos"] = "Shields",
		["Miscelánea"] = "Miscellaneous",
		["Dagas"] = "Daggers",
		["Varitas"] = "Wands",
		["Tela"] = "Cloth",
		["Malla"] = "Mail",
		["Armas de puño"] = "Fist Weapons",
		["Gujas de guerra"] = "Warglaives",
		["Hachas de una mano"] = "One-Handed Axes",
		["Mazas de una mano"] = "One-Handed Maces",
		["Bastones"] = "Staves",
	},
	["frFR"] = {
		["Plaques"] = "Plate",
		["Arcs"] = "Bows",
		["Bâtons"] = "Staves",
		["Divers"] = "Miscellaneous",
		["Relique d’arme prodigieuse"] = "Artifact Relic",
		["Mailles"] = "Mail",
		["Masses à deux mains"] = "Two-Handed Maces",
		["Arme d’hast"] = "Polearms",
		["Glaives de guerre"] = "Warglaives",
		["Fusils"] = "Guns",
		["Tissu"] = "Cloth",
		["Haches à une main"] = "One-Handed Axes",
		["Epées à une main"] = "One-Handed Swords",
		["Epées à deux mains"] = "Two-Handed Swords",
		["Masses à une main"] = "One-Handed Maces",
		["Haches à deux mains"] = "Two-Handed Axes",
		["Dagues"] = "Daggers",
		["Arbalètes"] = "Crossbows",
		["Boucliers"] = "Shields",
		["Baguettes"] = "Wands",
		["Armes de pugilat"] = "Fist Weapons",
		["Cuir"] = "Leather",
	},
	["itIT"] = {
		["Mazze a una mano"] = "One-Handed Maces",
		["Pugnali"] = "Daggers",
		["Armi da fuoco"] = "Guns",
		["Stoffa"] = "Cloth",
		["Mazze a due mani"] = "Two-Handed Maces",
		["Scudi"] = "Shields",
		["Reliquie dell'Artefatto"] = "Artifact Relic",
		["Lame da Guerra"] = "Warglaives",
		["Varie"] = "Miscellaneous",
		["Armi ad asta"] = "Polearms",
		["Archi"] = "Bows",
		["Tirapugni"] = "Fist Weapons",
		["Spade a due mani"] = "Two-Handed Swords",
		["Bacchette"] = "Wands",
		["Asce a due mani"] = "Two-Handed Axes",
		["Balestre"] = "Crossbows",
		["Maglia"] = "Mail",
		["Cuoio"] = "Leather",
		["Bastoni"] = "Staves",
		["Piastre"] = "Plate",
		["Spade a una mano"] = "One-Handed Swords",
		["Asce a una mano"] = "One-Handed Axes",
	},
	["koKR"] = {
		["지팡이류"] = "Staves",
		["한손 도검류"] = "One-Handed Swords",
		["장창류"] = "Polearms",
		["기타"] = "Miscellaneous",
		["양손 도검류"] = "Two-Handed Swords",
		["양손 둔기류"] = "Two-Handed Maces",
		["총기류"] = "Guns",
		["가죽"] = "Leather",
		["양손 도끼류"] = "Two-Handed Axes",
		["석궁류"] = "Crossbows",
		["전투검"] = "Warglaives",
		["유물 성물"] = "Artifact Relic",
		["방패"] = "Shields",
		["사슬"] = "Mail",
		["장착 무기류"] = "Fist Weapons",
		["천"] = "Cloth",
		["한손 둔기류"] = "One-Handed Maces",
		["단검류"] = "Daggers",
		["활류"] = "Bows",
		["판금"] = "Plate",
		["마법봉류"] = "Wands",
		["한손 도끼류"] = "One-Handed Axes",
	},
	["ptBR"] = {
		["Diversos"] = "Miscellaneous",
		["Maças de Duas Mãos"] = "Two-Handed Maces",
		["Relíquia de Artefato"] = "Artifact Relic",
		["Maças de Uma Mão"] = "One-Handed Maces",
		["Placas"] = "Plate",
		["Arcos"] = "Bows",
		["Machados de Uma Mão"] = "One-Handed Axes",
		["Glaives de Guerra"] = "Warglaives",
		["Espadas de Uma Mão"] = "One-Handed Swords",
		["Espadas de Duas Mãos"] = "Two-Handed Swords",
		["Armas de Haste"] = "Polearms",
		["Escudos"] = "Shields",
		["Varinhas"] = "Wands",
		["Adagas"] = "Daggers",
		["Báculos"] = "Staves",
		["Malha"] = "Mail",
		["Tecido"] = "Cloth",
		["Armas de punho"] = "Fist Weapons",
		["Armas de Fogo"] = "Guns",
		["Bestas"] = "Crossbows",
		["Machados de Duas Mãos"] = "Two-Handed Axes",
		["Couro"] = "Leather",
	},
	["ruRU"] = {
		["Тканевые"] = "Cloth",
		["Древковое"] = "Polearms",
		["Кистевое"] = "Fist Weapons",
		["Одноручное дробящее"] = "One-Handed Maces",
		["Щиты"] = "Shields",
		["Боевые клинки"] = "Warglaives",
		["Огнестрельное"] = "Guns",
		["Двуручное дробящее"] = "Two-Handed Maces",
		["Одноручные топоры"] = "One-Handed Axes",
		["Реликвия артефакта"] = "Artifact Relic",
		["Разное"] = "Miscellaneous",
		["Кожаные"] = "Leather",
		["Луки"] = "Bows",
		["Посохи"] = "Staves",
		["Двуручные мечи"] = "Two-Handed Swords",
		["Латные"] = "Plate",
		["Двуручные топоры"] = "Two-Handed Axes",
		["Кинжалы"] = "Daggers",
		["Жезлы"] = "Wands",
		["Кольчужные"] = "Mail",
		["Одноручные мечи"] = "One-Handed Swords",
		["Арбалеты"] = "Crossbows",
	},
	["zhCN"] = {
		["战刃"] = "Warglaives",
		["双手斧"] = "Two-Handed Axes",
		["弩"] = "Crossbows",
		["双手锤"] = "Two-Handed Maces",
		["其它"] = "Miscellaneous",
		["单手斧"] = "One-Handed Axes",
		["弓"] = "Bows",
		["盾牌"] = "Shields",
		["布甲"] = "Cloth",
		["法杖"] = "Staves",
		["神器圣物"] = "Artifact Relic",
		["拳套"] = "Fist Weapons",
		["单手剑"] = "One-Handed Swords",
		["魔杖"] = "Wands",
		["枪械"] = "Guns",
		["锁甲"] = "Mail",
		["皮甲"] = "Leather",
		["匕首"] = "Daggers",
		["单手锤"] = "One-Handed Maces",
		["长柄武器"] = "Polearms",
		["双手剑"] = "Two-Handed Swords",
		["板甲"] = "Plate",
	},
	["zhTW"] = {
		["單手劍"] = "One-Handed Swords",
		["雙手錘"] = "Two-Handed Maces",
		["弩"] = "Crossbows",
		["皮甲"] = "Leather",
		["雜項"] = "Miscellaneous",
		["單手斧"] = "One-Handed Axes",
		["戰刃"] = "Warglaives",
		["雙手劍"] = "Two-Handed Swords",
		["神兵聖物"] = "Artifact Relic",
		["單手錘"] = "One-Handed Maces",
		["雙手斧"] = "Two-Handed Axes",
		["法杖"] = "Staves",
		["鎧甲"] = "Plate",
		["長柄武器"] = "Polearms",
		["布甲"] = "Cloth",
		["槍械"] = "Guns",
		["魔杖"] = "Wands",
		["匕首"] = "Daggers",
		["拳套"] = "Fist Weapons",
		["鎖甲"] = "Mail",
		["弓"] = "Bows",
		["盾牌"] = "Shields",
	},
}