name: Discord Release Notification

on:
  workflow_run:
    workflows: ["Package and release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Create changelog
        # Grabs everything under the top level # header and outputs to a new file
        run: sed -n "3,/^# / {/^# /d; p}" changelog.md > changes.md

      - name: Send Discord notification
        run: |
          VERSION=${{ github.ref_name }} \
          REPO=${{ github.repository }} \
          DISCORD_WEBHOOK=${{ secrets.DISCORD_CHANGELOG_WEBHOOK_URL }} \
          bash ./.scripts/send_discord_release.sh changes.md
